### PR TITLE
Update for compatibility with Qiskit 1.0

### PR DESCRIPTION
**Pull request by d1ssk**
Before submitting, please check the following:
- Make sure you have tests for the new code and that test passes (run `tox`)
- format added code by `black -l 120 <filename>`
- If applicable, add a line to the [unreleased] part of CHANGELOG.md, following [keep-a-changelog](https://keepachangelog.com/en/1.0.0/).

Then, please fill in below:

**Context (if applicable):**
The current implementation is not compatible with the latest version of qiskit.

**Description of the change:**
This update includes a series of modifications to the codebase to ensure compatibility with Qiskit 1.0. Apart from the modifications on how to load the IBM quantum device, the external behavior of the module remains unchanged.

**Related issue:**

also see that checks (github actions) pass.
If lint check keeps failing, try installing black==22.8.0 as behavior seems to vary across versions.

### CODE REVIEW

**Comment by shinich1** [comment]
@d1ssk thanks for the update! 
https://docs.quantum.ibm.com/api/qiskit/circuit_classical#qiskit.circuit.classical.expr.Binary.Op.BIT_XOR
can we use this?

**Comment by shinich1** [comment]
nb: if the devices do not yet allow the BIT_XOR, we may separate out runner for simulator and devices? anyway, scope for separate issue.

**Comment by shinich1** [comment]
@d1ssk if this is ready for merge (if this works without major error as is), let us finish thei PR. will approve after final quick look.

**Comment by d1ssk** [comment]
This PR is ready to be merged. I would appreciate it if you could do a quick check.

**Pull request merged**
